name: Build Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/build-frontend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          target: frontend-production
          push: true
          tags: |
            ghcr.io/pirayt/meet-frontend:latest
            ghcr.io/pirayt/meet-frontend:ios-fix
          cache-from: type=gha
          cache-to: type=gha,mode=max
